### ISSUE TITLE
Update analysis scripts

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/teaching#1]
Once the experiments get up on Pavlovia we need to update this script to make sure it works in real time EDUC464_LearningInTheBrain/psychopy_experiments/Motor_task/SRT_Motor_task_plotdata.R

**Comment by earoy** [comment]
This script now works once the data have been pulled from pavlovia. I haven't added this feature, but if you want I can add a line that will automatically pull the data when you run the script (instead of you manually calling 'git pull' and then running the script)

**Comment by jyeatman** [comment]
Oh yes, add that!
